version: "3.8"
services:
  app:
    build:
      context: ./
    image: ${DOCKER_REGISTRY}
    volumes:
      - .:/src
    command: npm run receiver
    env_file:
      - .env
    environment:
      NODE_ENV: development
